version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tratra
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/tratra
      JWT_SECRET: super-secret-jwt-key-change-me
      CORS_ORIGIN: http://localhost:5173
      COOKIE_SECURE: "false"
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/drizzle:/app/drizzle
      - ./backend/.env:/app/.env:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/.env:/app/.env:ro

volumes:
  db-data:
